### ISSUE TITLE
Destroy instance

### ISSUE THREAD

**Issue by orloffv** [FineUploader/fine-uploader#1038]
How do I remove fineuploader from my one page application? I mean, event, object, etc.

**Comment by floatrx** [comment]
still important! how to remove instance and unbind all event from js... 
can't submit form without files... **it's sucks!**

**Comment by rnicholus** [comment]
@floatrx 

>still important! how to remove instance and unbind all event from js... 

Just remove the element.

>can't submit form without files... it's sucks!

No idea what you are talking about. Details?

**Comment by floatrx** [comment]
@rnicholus 
```
<!-- HTML -->
<form id="custom-form">
  <input type="text" name="input" value="val">
  <div id="fine-uploader-trigger"></div>
  <button type="submit">Submit</button>
</form>
```

```
// js 
$(function(){
  cfUploader = $('#fine-uploader-trigger').fineUploader({
      template: 'qq-template-manual-trigger',
      form: {
          element: 'custom-form',
      },
  });
})
```
### Issue
When i try Submit form without files i see this message:
"No files to upload."

how to fix it?

**Comment by rnicholus** [comment]
Fine Uploader's primary goal is to upload files. Sending form data is secondary. Any request sent by Fine Uploader _must_ contain file data. If you'd like to send a form without a file, there are many ways to do that, both using an "AJAX" approach and via a traditional form submit, but Fine Uploader will not help you there.

**Comment by mkucej** [comment]
Hi @rnicholus:

Perhaps I can explain better, why uploader should have a `destroy()` method. Let's say I want to use FineUploader with a form that sends messages and allows attaching files to messages, but attaching a file is **optional**. Fine uploader throws an error, if no file is present. The way to deal with this situation is to create uploader instance only, if a file is present. That works fine. But if a user sends a second message without a file, the error is emmited, because there is no way to destroy uploader after the first message has been sent. I believe this is an important improvement and this issue should be reopen. Thank you much!
