### ISSUE TITLE
custom cancel trigger

### ISSUE THREAD

**Issue by mnicolas80** [FineUploader/fine-uploader#1083]
When I try to cancel a file using this code: 
$('#fine-uploader').fineUploader('cancel',Id);

the uploader removes the file from queue! When I re-submit files for uploading, the uploader does not upload the files (without any error message), even if the files are presented in UI. If I try to cancel the files I get the following error for each file I tried to cancel:
" [FineUploader 4.1.1] 1 is not a valid item ID. "

So, my question is: How can we cancel a file from queue by using the fine-uploader's api, and not only the internal event binding on class "qq-upload-cancel".

Thank you

**Comment by chasevida** [comment]
This confused me somewhat as well. I thought when using `cancel` or `delete` that the file would be removed internally. So when I called `uploadStoredFiles()`, in order to get the `id` of the file selected, I was surprised to see all previous selections.

Filtering through this list by `status` checking for `cancelled` cleared some of the confusion. I came across this thread while working through a related issue, specifically when `multiple` is set to false, it is still possible to upload multiple files. Hence when I was checking the `uploadStoredFiles` I wasn't sure why there was more than one listed.
