### ISSUE TITLE
5 - Use Progress Element

### ISSUE THREAD

**Issue by srsgores** [FineUploader/fine-uploader#1117]
Currently, the uploader uses a ``<div id = "progress">``, and I think it should be changed to a ``<progress>`` element, [as is in the mdn html5 spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress).

**Comment by rnicholus** [comment]
No plans to add this to Fine Uploader UI directly. But [react-fine-uploader](https://github.com/FineUploader/react-fine-uploader) includes a `<ProgressBar />` component that [_does_ use the `<progress>` element](https://github.com/FineUploader/react-fine-uploader/blob/597af9bae4ced9206a482c4416e629ac8e9058f2/src/components/progress-bar.jsx#L47). Still, even in that case, I _may_ provide a fallback that resembles Fine Uploader UI's  custom progress bar, since the native `<progress>` element is not trivial to re-style cross-browser.
