### ISSUE TITLE
retry count does not reset with chunked uploads to S3

### ISSUE THREAD

**Issue by simshaun** [FineUploader/fine-uploader#1172]
We are debugging an issue our client is seeing in Firefox with the S3 uploader where it sometimes fails with

```
[Fine Uploader 4.3.1] Received response status 400 with body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.</Message>
```

The uploader has chunking enabled because the files being uploaded are typically 2 to 6 GB.

I have no idea as to the cause of that error (ideas?), but with the retry feature enabled, the failed chunk seems to successfully upload after 1 or 2 retries. The problem is the retry counter doesnt appear to reset to 0 if the chunk does upload successfully.

As it stands, it seems we need to set an arbitrary large number for maxAutoAttempts to accommodate a large number of retries on these files that are chunked in to over 1,000 pieces.

**Comment by notken** [comment]
Was this ever put in to the codebase and I've just not found the setting? I'm putting in deliberate random failures to test, with a retry count of 3. When it gives up, if I click Retry it only retries once before giving up again. The retry count does need resetting to zero after either a successful chunk, or at the very least after a manual retry.

**Comment by rnicholus** [comment]
This has not made it into a scheduled release yet. When it does, the case will be updated appropriately.

**Comment by rnicholus** [comment]
By the way, while I do agree that the retry count should be reset after a successful chunk, I do _not_ agree that this should be reset on a manual retry.

**Comment by notken** [comment]
I guess because it's not resetting after a successful chunk, it not resetting when you manually retry seems illogical. It just seems like it's totally ignoring the settings.

When testing it with built-in random failures, if I click Retry I'd expect it to suffer 3 more random failures before stopping again. But in actuality, the moment it's successfully done one after a failure I'd be quite happy for it to keep recovering from occasional failure until it's completed, and only fail if it really couldn't get through at all.

It just seems odd to ask for an auto-retry count in settings, and then ignore it and go for a developer-decided number when you manually Retry. Maybe it all needs to be in the settings.

**Comment by rnicholus** [comment]
This will be fixed simply by resetting the count once a chunk has
successfully uploaded.

**Comment by ShaharTal** [comment]
I am getting this error as well, not just with Firefox, mainly Chrome actually. Only with large files, directly to S3, what info can I give to better help/investigate?
