### ISSUE TITLE
3 - Scaling picture by height

### ISSUE THREAD

**Issue by Snake85** [FineUploader/fine-uploader#1181]
See my question on stackoverflow:

http://stackoverflow.com/questions/22946538/fine-uploader-scaling-picture-by-height/22946914?noredirect=1#22946914

**Comment by thomas83** [comment]
I thought it would be really nice to have an exact size scaled actually.  For CMS developers like us, it's important to allow users to upload something of whatever size they want.  Then, we smart-scale the image to a thumbnail that would fit the screen.

Since FineUploader by default offers image scaling, it would be nice to have this extra step of scaling it a little better.

Just my thoughts here.

Thanks!

Cheers,
Thomas
