### ISSUE TITLE
Firefox: TypeError: Argument 1 of Node.removeChild is not an object.

### ISSUE THREAD

**Issue by jwerre** [FineUploader/fine-uploader#1183]
In Firefox an Error is thrown on line 549

```
qq.toElement = (function(){
    var div = document.createElement("div");
    return function(html){
        div.innerHTML = html;
        var element = div.firstChild;
        div.removeChild(element);  <—— TypeError: Argument 1 of Node.removeChild is not an object.
        return element;
    };
}());
```

This is not happening in Chrome or Safari

**Comment by victoriafrench** [comment]
This issue should not be closed because it still happens with the latest firefox and the latest build. If you supply a script tag as your template (string id or direct element) firefox will fail. Because the code attempts to grab innerHTML of that script tag. In firefox, unlike chrome et al, innerHTML on script is always a blank string. However requesting children on it will return the items.

In my code I have to explicitly create a new div, pull the children from the script and append them to the new div before sending it in to qq.

**Comment by rnicholus** [comment]
What have you set the `type` attribute to on your `<script>` tag?

**Comment by victoriafrench** [comment]
text/template

**Comment by rnicholus** [comment]
All of the demos on FineUploader.com, which use templates, seem to be working in Firefox. So, how does your code differ from what is at http://fineuploader.com/demos?
