### ISSUE TITLE
iOS scaling bug

### ISSUE THREAD

**Issue by bjornbos** [FineUploader/fine-uploader#1231]
I have created a JSFiddle to demonstrate the issue: http://jsfiddle.net/Q48cw/8/

Normally, uploading a photo will result in a value for 'Bytes uploaded' after the upload. However, for some reason, on iOS when using the following example photo, it stays at zero:
http://auto-expire.s3.amazonaws.com/bug/upload.JPG

If you run this script locally and check the server request, the POST data would be empty.

**Comment by jakob-fuchs** [comment]
I hope it's not bad etiquette to post in this old issue here, but it seemed to be the most fitting one. I need to disable this resize behavior. For my use case I'd rather not display the preview image at all instead of resizing it. Also, does anyone know if these restrictions are still in place in newer iOS devices? 

I am aware that I can implement my own code for thumbnail generation, but the fine uploader implementation is really fast and performant.
