### ISSUE TITLE
Custom Build

### ISSUE THREAD

**Issue by hn1** [FineUploader/fine-uploader#1348]
Hi
We wanted to download the latest FineUploader but have noticed that there is no longer the option of choosing which modules to include and now instead of 70k we need to download the full 130k file. Is this correct?

Many thnaks

**Comment by feltnerm** [comment]
Correct. The custom build generator was deprecated in favor of just linking to zip files containing the entire source. A few reasons:

1. Some people were encountering bugs due to them thinking they had selected a module, when in actuality they had not.
1. The extra 60k does not add much overhead. On a 1Mbps connection it'll only take ~.5 seconds to get the extra 60k. Add in the fact that should have caching and compression on your server, and this time becomes even less.
1. Maintenance of the build generator was slowing down our releases, and adding extra overhead for not a ton of perceived benefit (the benefit being smaller sizes for _some_ customers, but that size is negligible when you take into account the fact that modern browsers and servers can cache and compress resources which considerably reduces the size of the payload.
1. The latest release was published on npm, and for consistency we decided that the build generator should follow the layout and structure of the code distributed via that.

For the future, we are thinking about putting up multiple packages on npm (so you could install: `npm install fine-uploader-{azure,s3,traditional}`. Maybe in the future we could have separate modules (DnD, Image resizing, etc.) be modularized on npm so that you could optionally include these if you wanted.

@hn1 -- is there any compelling reasons you can think of (besides size of code-base) that would merit a return of the custom build generator?

**Comment by hn1** [comment]
It would be nice to have just 2 versions - The Core and UI. On applications that serve international markets, in some localities, 60k can be a big deal.
Thanks

**Comment by rnicholus** [comment]
Note that the gzipped size of the minified file is about 40 kB total.  The difference between the gzipped size of the all-inclusive fine uploader.min.js vs a custom build is much smaller in this case.

**Comment by rnicholus** [comment]
I think we can oblige in a future version by including seperate  builds of core and UI for traditional, S3, and Azure endpoints.  It occurred to us that we should also throw the DnD module on npm, as that can stand on its own as well.

**Comment by hn1** [comment]
That would be great. We will wait for that to update our version. Thanks

**Comment by fschwahn** [comment]
Hi,
I just want to add that I would also be interested in this - at least a build with and without the UI component would be great.

All the best,
Fabian

**Comment by rnicholus** [comment]
We will look into this as part of the release after 5.2 (likely 5.3).

**Comment by rnicholus** [comment]
This will be covered by #1607.
