### ISSUE TITLE
Fine-Uploader PHP issues unanswered

### ISSUE THREAD

**Issue by courtchatter** [FineUploader/fine-uploader#1364]
I raised a question/issue on stackoverflow which has gone unanswered. http://stackoverflow.com/questions/28347173/fine-uploader-php-installation-directory

I raised 2 issues (1 to create an issue within Github for the above) plus another in what appears to be the correct place https://github.com/FineUploader/fine-uploader-php-docs/issues

These too have gone unanswered as has an attempt to make contact through Widen.

I really don't know what else to do or how long I am expected to wait for a response but I have to say that I am not impressed by the level of response. I'll give this one last shot and wait for a couple of days before turning to an alternative solution.

**Comment by rnicholus** [comment]
Sorry about that.  Fine Uploader PHP is a separate product from the traditional library.  You're right, it's unacceptable for us to have let your support requests go unanswered for so long.  At this time, due to resource limitations, we are not able to provide the same support for Fine Uploader PHP that we have consistently provided for the JavaScript library.  Fine Uploader PHP is in a beta state at the moment.  We have decided to shelve Fine Uploader PHP until we are able to secure enough developers to provide consistent support and evolution of that product.  We will link back to the project on our website once this happens.

Fine Uploader JavaScript (the library represented here) will continue to grow and be supported as it always has been.

**Comment by courtchatter** [comment]
Thankyou at least for making a response.
Please update the 2 issues that I created in https://github.com/FineUploader/fine-uploader-php-docs/issues and also reply to http://stackoverflow.com/questions/28347173/fine-uploader-php-installation-directory to save anyone else from wasting their time. I see that you have now removed the invitation to try the PHP version from your home page.

**Comment by rnicholus** [comment]
Absolutely.  They will be updated know with a reference to this case.
