### ISSUE TITLE
Fineuploader file selection issue with more than 900 files

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1378]
Hi Ray

When we are dragging and dropping files in the fine uploader control then we are able to drop more than 900 files but we are unable to select more than 900 files from a folder in a single selection.
We have set the itemlimit :0 in the validation property. Please check the code snippet below.

Please help us on this. Thanks in advance for your help

manualuploader = $('#fine-uploader').fineUploader({
            //debug: true,
            request: {
                endpoint: UploadDataUrl,
                forceMultipart: false
            },
            autoUpload: false,
            maxConnections: 5,
            chunking: {
                enabled: true,
                concurrent: {
                    enabled: true
                },
                partSize: 500000,
                success: {
                    endpoint: null
                }
            },
            resume: {
                enabled: false
            },
            retry: {
                enableAuto: true
            },
            cors: {
                expected: true, //all requests are expected to be cross-domain requests
                sendCredentials: false, //if you want cookies to be sent along with the request
            },
            validation: {
                itemLimit: 0
            },
            multiple: multiSelect
        });

Regards
Manidipa

**Comment by rnicholus** [comment]
1. Not sure why are you specifying an itemLimit of 0 instead of simply omitting the validation?

2. You haven't actually described the problem. What happens when you try to select more than 900 files? Are you simply not able to select, or does the submit to fine uploader fail. 

Since you haven't provided any details about the issue, I have to assume that you are simply unable to select more than 900 files in the file chooser dialog of whatever operating system you are using. In that case, fine uploader is not to blame as it has little control over the file chooser modal.
