### ISSUE TITLE
success should consider 200-series status codes successful

### ISSUE THREAD

**Issue by chrylis** [FineUploader/fine-uploader#1402]
I tried returning ACCEPTED (202) from my success endpoint, since I don't have anything to say, but Fine Uploader considers that a failure code. Anything in the 200 series is supposed to be treated as success; in particular, it's entirely likely that a 201 is appropriate.

**Comment by rnicholus** [comment]
What version of Fine Uploader?






On Sun, Apr 26, 2015 at 3:33 PM -0700, "Christopher Smith" <notifications@github.com> wrote:












I tried returning ACCEPTED (202) from my success endpoint, since I don't have anything to say, but Fine Uploader considers that a failure code. Anything in the 200 series is supposed to be treated as success; in particular, it's entirely likely that a 201 is appropriate.

**Comment by rnicholus** [comment]
Acceptance of these statuses was added as part of 5.2.0 in #1314. If you are using 5.2.x and still seeing an issue, please include all details needed to reproduce and this can be re-opened.

**Comment by chrylis** [comment]
I'm still on 5.1.3; I hadn't seen the new release. I'll move us over as soon as practical. Thanks!
