### ISSUE TITLE
custom attributes should be prefixed with data- to respect the HTML5 standard

### ISSUE THREAD

**Issue by stof** [FineUploader/fine-uploader#1430]
the dropzone feature relies on attributes like ``qq-drop-area-text`` and ``qq-hide-dropzone``. To respect HTML5, custom attribute names should start with ``data-``

**Comment by rnicholus** [comment]
Please cite the specific section of the spec that mandates custom attributes be prefixed with "data-".

**Comment by rnicholus** [comment]
I'm going to close this as there is no need to rename all of Fine Uploader's contributed custom attributes. You could very easily open the same case in, for example, the angular project, which also makes use of non-data attributes. 

The primary reasons for using the "data-" prefix are:
1. Access to the value on the element object via [the `dataset` property](http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#dom-dataset).
2. Prevent clashes with other native attributes.

Fine Uploader namespaces all custom attributes, so there is no chance of collision with native attributes. Also, we don't currently make use of the `dataset` property, mostly due to the poor browser support (IE11+).

**Comment by stof** [comment]
Well, AngularJS relies on such attributes in their templates
