### ISSUE TITLE
Live demo for FineUploader Azure?

### ISSUE THREAD

**Issue by MarwaAhmed** [FineUploader/fine-uploader#1436]
Hi,
I didn't find a live demo for  Azure at: [FineUploader demo](http://fineuploader.com/demos). So where i could find it?

BTW, the documentation stated that  [Everything should work just fine if you simply use the provided templates as is, without changing anything](http://docs.fineuploader.com/branch/master/features/styling.html). 
But the default.html body is empty? and there was nothing displayed when i run the default.html!

**Comment by rnicholus** [comment]
There is no live demo for Azure, as there are not many customer utilizing Azure. S3 is heavily used, which is why it is represented with a live demo.  If you would like help troubleshooting your code, please see [our support page](http://fineuploader.com/support.html) for details on how to properly do this. The issue tracker is for feature requests and bug reports.
