### ISSUE TITLE
Add support for qqPath when choosing folder in dialog in Chrome

### ISSUE THREAD

**Issue by michaeljmx** [FineUploader/fine-uploader#1452]
FineUploader currently includes qqPath in file parameters when dropping folder in Chrome. However, when a folder is added using a folder selection dialog, the qqPath parameter isn't available.

Accroding to my tests it is possible to read the full file path in this case from the webkitRelativePath file property. Could you please implement saving this data in the qqPath parameter for using in event handlers and requests to server?

**Comment by rnicholus** [comment]
I was hesitant to expose the ability to upload folders via the file chooser, since this is generally a bad idea due to the fact that the UI thread can lock up for long periods of time and cause the browser to crash. With this in mind, I don't forsee adding any further enhancements to support this workflow. You can always access the underlying `File` via [the `getFile` API method](http://docs.fineuploader.com/branch/master/api/methods.html#getFile).
