### ISSUE TITLE
Too many items problem

### ISSUE THREAD

**Issue by standus** [FineUploader/fine-uploader#1468]
With this setting:
{ "validation": {  "itemLimit": "1", "allowedExtensions": ["jpeg", "jpg","avi","png"] }, "scaling": { "sendOriginal": "false", "sizes": [ {"name": "sized", "maxSize": "2000"} ]} }
I want upload only scaled image and original forget = 1 image!
I got error: Too many items (2) would be uploaded. But I uploaded only 1.

**Comment by rnicholus** [comment]
The issue is in your configuration. `"false"` is not a valid value for the `scaling.sendOriginal` configuration property. That property expects a boolean, not a string. I would suggest taking a look at similar configuration options on your end. Be sure you are respecting the expected types according to the documentation. http://docs.fineuploader.com/
