### ISSUE TITLE
how to fixed rotate 90 degree in ios

### ISSUE THREAD

**Issue by ifany** [FineUploader/fine-uploader#1579]
how to fixed rotate 90 degree in ios?

**Comment by rnicholus** [comment]
Please don't ignore or delete the issue template. As it stands, without the details required by that template, it is not possible for me to even determine what you are referring to, since Fine Uploader already orients images correctly. 

If you are attempting to report a _bug_ or ask for a _new feature_, please open up a new issue, follow the template, and provide as much detail as possible. For a "how do I do this?" type of question, post on Stack Overflow under the `fine-uploader` tag.
