### ISSUE TITLE
Core Mode demo

### ISSUE THREAD

**Issue by george-fb** [FineUploader/fine-uploader#1583]
All demos are using the UI Mode, could you add one for Core Mode too?

**Comment by rnicholus** [comment]
How would they be different, other then a couple less options and no template?

**Comment by george-fb** [comment]
I want to use the core mode, but i can't figure out how to display the image name and thumbnail after the images have been selected.

More precisely how to use the drawThumbnail method. Seeing an example would help me understand.

**Comment by rnicholus** [comment]
The [`drawThumbnail` method documentation](http://docs.fineuploader.com/branch/master/api/methods.html#drawThumbnail) explains parameters that can be passed, and the expected outcome. For example, if you would like to generate a thumbnail onto an `<img>` tag for a file at ID 0, and want the thumbnail to be no more than 500 pixels tall and 500 pixels wide: your code would look like this:

```javascript
uploader.drawThumbnail(0, emptyImgElement, 500);
```

If you need to know exactly when the thumbnail has been drawn on the `<img>` you provided, `drawThumbnail` returns a "thenable" value, which can also be called a `Promise` (though Fine Uploader's promise implementation is unfortunately non-standard, this should be sufficient for your use-case).

These types of questions belong on Stack Overflow under the fine-uploader tag, which is why I include a template when you create an issue (to keep issues and feature requests here - which you deleted). Please include any further support questions on Stack Overflow, and be sure to [understand the rules and expectations of posting questions on Stack Overflow](http://stackoverflow.com/help/how-to-ask) before doing so.

**Comment by george-fb** [comment]
I deleted the template because my "issue" was no bug and no feature request, nor would it be allowed on stack overflow.

I only suggested for a core mode demo to be added amongst the UI demos and gave you an example as to why i needed one.

I'm sorry if it's something i should know if i want to use core mode, but i felt a core mode would be helpful.

And sorry if this kind of request is not allowed here, but i don't know were else i could do it.

**Comment by rnicholus** [comment]
Your support request for generating thumbnails using the API was completely appropriate for Stack Overflow, as long as you include appropriate details and code that shows your attempt to solve the issue. A request to "add more demos" isn't appropriate _anywhere_. This is an free open source project and cannot continue to survive with a single person's efforts. If you would like to see more demos, you are welcome to contribute more demos, or ask _how_ you can contribute more demos if that is not clear, or ask specific support questions (on SO) that will lead you to develop a custom integration that will lead to a demoable block of code, which you can then contribute for others in the community to benefit from.

**Comment by george-fb** [comment]
It was merely a suggestion, if you feel it's not worth, no problem.

The way I phrased it might have come as demanding, i'm sorry, i didn't mean to be rude.

**Comment by rnicholus** [comment]
Understood, and no problem. But this project really does need the support of the community. While I'm happy to continue to maintain and develop critical and complex features, I had a full-time job and other endeavors on the side (such as maintenance of other libraries, a book, etc). 

So, let's say you want to see a specific demo added to FineUploader.com. If you are unable to code that up yourself, the next best thing would be to open up a feature request here in the issue tracker, and explain, in copious detail, exactly what you are hoping to demonstrate and why you think this may be useful to other Fine Uploader users. If you have code to show, such as with an incomplete demo/integration, then you also have the option of posting on Stack Overflow. In that case, an answer would update and complete your code, based on your question. In either case, whatever code you have so far would likely be helpful as well.
