### ISSUE TITLE
scaleImage not working (?)

### ISSUE THREAD

**Issue by kjepo** [FineUploader/fine-uploader#1593]
## Type of issue [REQUIRED]
bug

## Uploader type [REQUIRED]
traditional

## Bug details [DELETE EVERYTHING IN THIS SECTION IF THIS IS A FEATURE REQUEST]
When making this call,

this.scaleImage(id, { maxSize: 2048 });

from within the callback onUpload, the scaleImage has no effect.

### Fine Uploader version [REQUIRED]
5.9.0

### Browsers where the bug is reproducible [REQUIRED]
Chrome

### Operating systems where the bug is reproducible [REQUIRED]
Mac OS X 10.11.5

### Exact steps required to reproduce the issue [REQUIRED]
Select 1 file
Click on Upload

### All of your Fine Uploader initialization JavaScript code [REQUIRED]

        $('#fine-uploader-manual-trigger').fineUploader({
          template: 'qq-template-manual-trigger',
          request: {
            endpoint: './server/endpoint.php',
          },
          thumbnails: {
            placeholders: {
              waitingPath: './placeholders/waiting-generic.png',
              notAvailablePath: './placeholders/not_available-generic.png'
            }
          },
          autoUpload: false,
          debug: true,
          callbacks: {
            onUpload: function(id, name) {
	      console.log("id = " + id + ", name = " + name);
              this.scaleImage(id, { maxSize: 2048 });   // <---- has no effect
	    }
          }
	});

        $('#trigger-upload').click(function() {
            $('#fine-uploader-manual-trigger').fineUploader('uploadStoredFiles');
        });
    </script>
</body>
</html>

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Not UI-related

### Detailed explanation of the problem [REQUIRED]
Even though the log says that the image is successfully scaled down, the image received on the server side is not.

Here's an excerpt from the log:

[Fine Uploader 5.9.0] Attempting to generate scaled version for Alice-011.jpg
[Fine Uploader 5.9.0] size = 2048
[Fine Uploader 5.9.0] Attempting to draw client-side image preview.
[Fine Uploader 5.9.0] Attempting to determine if Alice-011.jpg can be rendered in this browser
[Fine Uploader 5.9.0] First pass: check type attribute of blob object.
[Fine Uploader 5.9.0] Second pass: check for magic bytes in file header.
[Fine Uploader 5.9.0] Sending simple upload request for 0
[Fine Uploader 5.9.0] 'Alice-011.jpg' is  able to be rendered in this browser
[Fine Uploader 5.9.0] Moving forward with EXIF header parsing for 'Alice-011.jpg'
[Fine Uploader 5.9.0] EXIF Byte order is little endian
[Fine Uploader 5.9.0] Found 9 APP1 directory entries
[Fine Uploader 5.9.0] Successfully parsed some EXIF tags
[Fine Uploader 5.9.0] Success generating scaled version for Alice-011.jpg

**Comment by rnicholus** [comment]
Fine Uploader appears to be working as expected. There are a couple issues with your code, but the main one is due to a misunderstanding of how the `scaleImage` API method works. As you can see [in the documentation](http://docs.fineuploader.com/branch/master/api/methods.html#scaleImage), `scaleImage` returns a `Promise`. When that `Promise` is resolved, the scaled image, converted to a `Blob` is passed to your `resolved` handler. In your `onUpload` callback handler, you're ignore the return value, which means the scaled `Blob` is never used. 

If you want Fine Uploader to automatically generate and upload scaled versions of files when they are submitted, see the [`scaling` option](http://docs.fineuploader.com/branch/master/api/options.html#scaling). Otherwise, you can use `scaleImage` to create a scaled version of any file already submitted to Fine Uploader, and then feed that `Blob` back into Fine Uploader via the [`addFiles` method](http://docs.fineuploader.com/branch/master/api/methods.html#addFiles) (or do anything else you please with this scaled version of a submitted file).
