### ISSUE TITLE
Override Accept header

### ISSUE THREAD

**Issue by drsect0r** [FineUploader/fine-uploader#1609]
## Type of issue
Bug

## Uploader type
traditional

### Fine Uploader version
5.10.0

### Browsers where the bug is reproducible
Google Chrome

### Operating systems where the bug is reproducible
Linux Fedora 23

### Exact steps required to reproduce the issue
For example:
1. Upload any file.

### All of your Fine Uploader initialization JavaScript code
``` js
var uploader = new qq.FineUploader({
    debug: true,
    element: document.getElementById('fine-uploader'),
    request: {
        endpoint: 'http://example.com/files/uploads',
        customHeaders: {
            'Accept': 'application/vnd.something.v1+json'
        },
        method: 'POST'
    }
});
```

### Detailed explanation of the problem
I am trying to override the Accept header. The documentation discusses sending additional headers but not overriding them - is this possible? Documentation found at [docs.fineuploader.com](http://docs.fineuploader.com/branch/master/api/options.html#deleteFile.customHeaders).

**Comment by rnicholus** [comment]
Why would you want to explicitly specify an `Accept` header? Fine Uploader handles the response to this request _and_ already sets the appropriate `Accept` header. You can't override the `Accept` header specified by Fine Uploader at the moment, and I don't see allowing that in the future since the only code that should care about the response is internal Fine Uploader response handling code.

**Comment by drsect0r** [comment]
@rnicholus The backend infrastructure is using the `Accept` header for versioning.

**Comment by rnicholus** [comment]
Ok - it looks like you'll need to use a more appropriate header to relay this information to your server. The `Accept` header is typically used to ensure the server responds with the appropriate data exchange format. In this case, the appropriate value is "application/json".

**Comment by glen-84** [comment]
@rnicholus The accept type is compatible with JSON (`+json`) ... it's similar to [GitHub's](https://developer.github.com/v3/#current-version) accept type.

I'm not sure what the exact rules are here.

**Comment by rnicholus** [comment]
Specifying a custom `Accept` header should result in both MIME types included on the header sent to the server w/ the request. This seems valid to me, and your server should be able to handle this. Is your server simply not parsing the header value correctly, or is there a syntax error in the header value? I would be surprised if the header value is invalid.

**Comment by drsect0r** [comment]
@rnicholus I don't agree, according to this [RFC](https://tools.ietf.org/html/rfc4288#section-3.2) the `Accept` header can be used for API versioning, vendor schema and the actual application type.

**Comment by rnicholus** [comment]
@drsect0r Please see my comment above.

**Comment by rnicholus** [comment]
Just to recap - Fine Uploader is sending a non-standard header value when it combines it's internal choice of "application/json" and a custom supplied `Accept` header, please let me know of the specifics. Otherwise, your server code will need to properly parse this header per [RFC-2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1). Regarding multiple values in an HTTP header, please see the end of [section 4.2 in the same RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

**Comment by drsect0r** [comment]
@rnicholus Thank you for your time. We will solve this on our end.
