### ISSUE TITLE
Handle new AWS S3 "dualstack" IPv6 endpoints

### ISSUE THREAD

**Issue by chris-denning** [FineUploader/fine-uploader#1645]
## Type of issue

Feature request
## Uploader type

S3
### Detailed description of the feature

{also include why this feature is necessary and what problems it solves}

AWS have recently [announced](https://aws.amazon.com/about-aws/whats-new/2016/08/internet-protocol-version-6-ipv6-support-for-amazon-s3/) IPv6 support for S3.  Fine uploader S3 users (like me) will likely want to make use of this new feature.

The IPv6 support is handled by new "dual stack" S3 endpoints, with slightly different hostnames, for example
`http://bucket.s3.dualstack.aws-region.amazonaws.com`
See AWS [full list of S3 endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region)

When configuring Fine Uploader for these new-style endpoints, the built-in parsing does not correctly identify the bucket name from the endpoint, and so the signing request fails if you're checking the bucket name.

You can work round this by specifying objectProperties.bucket explicitly, in addition to the endpoint name, but it would be great if it "just worked" as with the older endpoint names.

The fix would be in `fine-uploader/client/js/s3/util.js`, enhancing the regular expression patterns in `getBucket()` to recognise the new endpoint styles with "dualstack" in the hostname.

**Comment by rnicholus** [comment]
Thanks for the report/request. Fine Uploader S3 appears to be a never-ending feature, but I can see why this would be useful. That said, since there is a workaround, and IPv6 utilization is probably pretty light, this won't make it onto my plate for a loooong time. _But_, a pull request with the required changes, a new unit test or 2, and updated documentation (that's debatable though) would push this through much faster.

**Comment by rnicholus** [comment]
No pull request or additional requests to implement here, so I'm closing this since a workaround exists anyway
