### ISSUE TITLE
Improve "Getting Started Guide"

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1646]
These improvements will focus primarily on [page 1](http://docs.fineuploader.com/quickstart/01-getting-started.html). Prompted by @strohhut at https://github.com/FineUploader/fine-uploader/issues/1640#issuecomment-240201030.

Before this is merged into develop/master, in-progress docs will be built at http://docs.fineuploader.com/branch/docs_1646-better-getting-started/.

Page 1:
- [x] Step 1: List all reliable methods of obtaining a copy of Fine Uploader.
- [x] Step 2: The differences between the various builds/types of Fine Uploader (All, Traditional, S3, Azure, UI, Core).
- [x] Step 3: Gathering the proper files based on your desired functionality/build. Break this down into sections that match the build types discussed in Step 2.
- [x] Step 4: Including the appropriate JS and CSS files in your project.

Page 2 (traditional, S3, Azure):
- [x] Links to options. Where do you find out more info about these?

Page 3:
- [x] Traditional & S3: Update PHP server version.
- [x] Traditional & S3: Links to server-examples repo for more options.

FineUploader.com:
- [x] Link to page 1 of the guide on the index page & download page.

Templates: 
- [x] Remove everything other than the template HTML. Reference the getting started guide and the styling feature page in initial comments section. The templates will have to be officially updated & distributed in the next release.

**Comment by strohhut** [comment]
Leaving out code samples from step 1 and step 2 and the more in-depth explanations are great. Looks like the new guide will be very helpful. I'll comment here if I notice something.

**Comment by rnicholus** [comment]
I consider page 1 to be complete at this point. Please let me know if anything seems to be missing or any further improvements are warranted.

**Comment by strohhut** [comment]
A couple of things I noticed about the new step 3:

- At the beginning the word "properly" is a bit overused.
- I think for a getting started guide it's not really necessary to say that the minified
versions are needed for production enviornment. Adding this information every time adds much noise and saying that they are "needed for production" sounds like there is a functional difference. Maybe it's enough to mention at the end of step 3 that minified versions of the above files exist for production. 
- I think this line has a mistake regarding the optional and debugging info:
 
 "fine-uploader/fine-uploader-gallery.min.css (optional, but useful for live-debugging)"  
- For the image files I'd not only mention that they are needed but that they have to be in the same directory
as the fine uploader css files so that the image file paths used in the css files will work.

**Comment by rnicholus** [comment]
The guide is a bit repetitive as I don't anticipate a single user reading every single section. Rather, I see them choosing an endpoint type and feature set, and then zeroing in on the remaining steps that address that specific selection. Great feedback, thanks! I'll make these changes.

**Comment by rnicholus** [comment]
Also, can you explain where the mistake is on this line?

>"fine-uploader/fine-uploader-gallery.min.css (optional, but useful for live-debugging)"

**Comment by strohhut** [comment]
I know what you mean. It's just that a programmer who cares about performance and minified files will automatically look for minified versions.  Including the information about the minified files as it is now in step 3 seems like it is a big deal that minified versions exist. I'd simply focus on the files that make a functional or visual difference in the Getting started Guide.

**Comment by rnicholus** [comment]
I just updated page 1 with your suggestions.

**Comment by rnicholus** [comment]
I'm mostly done with all of this. All that is left is to update fineuploader.com and then release 5.11.6 with the changes to the docs and templates.

**Comment by strohhut** [comment]
I noticed that there is something missing in this sentence: "The sections below will show you how to necessary Fine Uploader files in a globally scoped environment" in step 4.

The heading in step 5 "Initial Options" seems a bit strange to me because it suggests that _later_ there are other options. Maybe you can rename it to something like "Basic Options".

**Comment by rnicholus** [comment]
I'll fix those lines, thanks. Anything else obviously missing? If not, I'll push out the doc, template, and website changes soon.

**Comment by rnicholus** [comment]
Released with 5.11.6.
