### ISSUE TITLE
Reposition upload button or make entire area clickable

### ISSUE THREAD

**Issue by aaronhoffman** [FineUploader/fine-uploader#1655]
## Feature request details 
I can't find any documentation on how to reposition the upload button. I would also prefer if there was an option to remove the upload button altogether and make the entire drop area clickable (like dropzone.js)

**Comment by rnicholus** [comment]
You can style the button (or any part of the template) in your template markup & via CSS. I would suggest re-thinking the "entire drop zone is clickable" requirement. You will likely run into problems since the file elements in the dropzone also have buttons of their own (cancel, delete, etc).

Please use this issue tracker for feature requests and bug reports. Stack Overflow, under the fine-uploader tag, is the best place to post support-type questions.

**Comment by Igmat** [comment]
@rnicholus but elements inside dropzone can use `stopPropagation` function for avoiding user confusion and keep whole drop area clickable, because second is pretty common use case and a lot of users expects such behavior.
