### ISSUE TITLE
FineUploaderBasic: "multiple" option always defaults to false, and can't change it.

### ISSUE THREAD

**Issue by agamemnus** [FineUploader/fine-uploader#1684]
With FineUploaderBasic, I can't upload multiple files without forcing the "isMultiple" to true in the setMultiple function.

Again, not sure if this is a bug or "feature". I couldn't find any explanation that showed the differences between the basic and non-basic version. Please let me know and I will add more details (if needed)

**Comment by rnicholus** [comment]
Please don't delete the template. I'll re-open once you've re-inserted the template and followed the instructions for posting an issue or feature request.

**Comment by agamemnus** [comment]
I can't use the template if I don't know if it is a bug or a feature. What am I supposed to do?

**Comment by rnicholus** [comment]
If it's not obviously a bug or a feature, then you should be asking the question on Stack Overflow. Support options are described at http://fineuploader.com/support.

**Comment by agamemnus** [comment]
Ok, I'll just assume it is a bug. I think it's a bug, but I don't know. I already did search Stack Overflow for hours and couldn't find an answer.

**Comment by agamemnus** [comment]
I will edit these two, assuming it is a bug.

**Comment by agamemnus** [comment]
Edited, but I don't have access to the full code at this moment.

**Comment by rnicholus** [comment]
My guess is that you are not setting your options correctly, but I can't tell since you haven't posted your full code. I can assure you that the `multiple` option works fine, and I'm using it myself in other projects. I don't really have time for completely avoidable back-and-forth, such as continuing to ask for information that is already required by the template. Once you are able to post your full code, please open up a new issue (if you are fairly certain it's an issue with Fine Uploader), and this time follow the template. I doubt this is an issue with Fine Uploader, so Stack Overflow is usually most appropriate for support questions.
