### ISSUE TITLE
ValidateBatchAfterSubmit

### ISSUE THREAD

**Issue by zaryk** [FineUploader/fine-uploader#1767]
## Type of issue
- [ ] Feature request

Add validateBatchAfterSubmit event which would come after OnSubmit

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

Initially, I was showing a button on the OnValidateBatch, by checking to see if there were any files and showing the button.  I have now added a condition to the onsubmit to check if the file has qqPath and return false if the extrabuttons folder is false.  The OnValidateBatch still runs, so the button still shows.  Would be nice to have a validateBatchAfterSubmit, which would only have the files that were successfully submitted.

<pre>
if (fileOrBlobDataArray.length >= 1) {
                        $("#trigger-clearQueued").show();
                    }
</pre>

**Comment by rnicholus** [comment]
please mark these issues appropriately

**Comment by rnicholus** [comment]
sorry, again not really understanding the question/request here. are you asking for a third callback for you to reject files?

**Comment by rnicholus** [comment]
sorry, but this is a really very poorly written feature request. I don't really have time to ask questions just to figure out exactly what is being asked, why the requested feature is useful for a general audience, and whether the issue is a support request or a feature request. This is why I setup the template. Please spend more time curating/explaining/organizing your issues before you file them. The last several issues you've commented on have left me puzzled.
