### ISSUE TITLE
showMessage only returns one error per file selection attempt

### ISSUE THREAD

**Issue by sdfreeland** [FineUploader/fine-uploader#1790]
## Type of issue
- [x] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.13.0

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
Win 8

#### All relevant Fine Uploader-related code that you have written
showMessage: function (message)
                {
                    console.log(message);
                }

#### Detailed explanation of the problem
showMessage returns only one error even if multiple files producing different errors are selected at the same time.  For example, if you only allow jpeg extensions, but select three mp3 files to upload and a file that is larger than the file size limit, the error will only return one error.  The other files have no errors or confirmations.
</details>

**Comment by rnicholus** [comment]
This is due to the default value for the [`validation.stopOnFirstInvalidFile` configuration option](https://docs.fineuploader.com/branch/master/api/options.html#validation.stopOnFirstInvalidFile). Setting that to `false` will process all files instead of stopping when an invalid file is encountered.
