### ISSUE TITLE
Set x-amz-decoded-content-length header

### ISSUE THREAD

**Issue by cretueusebiu** [FineUploader/fine-uploader#1833]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [X] Support request

## Uploader type
- [ ] Traditional
- [X] S3
- [ ] Azure

#### Question
Is there any way to set the `x-amz-decoded-content-length` header when using chunks ? I want to be able to validate the file size.

http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html

**Comment by cretueusebiu** [comment]
I found this workaround:

Add the header to the unprefixed names:
```javascript
qq.s3.util.UNPREFIXED_PARAM_NAMES.push('x-amz-decoded-content-length')
```

Then just pass the header via the params option:

```javascript
// file is an instance of File
uploader.addFiles([file], { 'x-amz-decoded-content-length': `${file.size}` })
```

**Comment by rnicholus** [comment]
Please open a PR

**Comment by cretueusebiu** [comment]
Unfortunately this doesn't work as I expected. 

Even if I set this header with a certain size I can still upload a file with another size.

I'm not sure if there's any other way to tell S3 what's the max file size.

**Comment by truthSeekr** [comment]
@cretueusebiu Did you find any solutution since that time ?

**Comment by cretueusebiu** [comment]
@truthSeekr No. I just have bucket notifications enabled and once the upload is done my server is notified and then I check the file size and delete it, if necessary.

**Comment by truthSeekr** [comment]
I can't even make it to add this custom header. It just ain't adding and no error. I just added it with
`            customHeaders: {
                'Access-Control-Allow-Origin': "http://localhost:3000",
                'Access-Control-Allow-Credentials': "true",
                'x-amz-decoded-content-length': "10"
            }`

I used chunked

**Comment by truthSeekr** [comment]
@cretueusebiu is your notification set to notify your server when file uploaded or chunk uploaded ?

**Comment by cretueusebiu** [comment]
@truthSeekr When new objects are created, so that's when the last chunk is uploaded.

**Comment by truthSeekr** [comment]
Ok I can see that AWS S3 doesn't charge for uploading transfer. So there is no need to check chunk size since I doesnt pay for it. Does it mean that if I set somehow this 'x-amz-decoded-content-length` and file will be larger, it won't save it ? therefore I won't be charged for storing file. You wrote before that this header doesn't work properly for you. Do you mean only that u can upload file with more size than specified and aws saves it ignorign this header ? or you can upload file that is larger and it doesn't save at finish of completing chunks. Thanks for reposting me.

**Comment by cretueusebiu** [comment]
I think it only checks it at the end.
