### ISSUE TITLE
qq.format

### ISSUE THREAD

**Issue by mottoregina** [FineUploader/fine-uploader#1884]
## Type of issue
- [ ] Bug report
in qq.format function

newStr.indexOf("{}", nextIdxToReplace + val.length)

val undefined stop the working of uploading files.

quickfix
                if (val !== undefined)
                    nextIdxToReplace = newStr.indexOf("{}", nextIdxToReplace + val.length);
                else
                    nextIdxToReplace = -1;

## Uploader type
- [ ] Traditional
server side send:

{"success": false,"error": "Incorrect combined file size!", "reset": true}

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
ff and chrome

#### Operating systems where the bug is reproducible
windows

#### Fine Uploader version
{example: 5.5.1}

#### Question
{ask your support question here & be as detailed and clear as possible}

#### Related code
{post any code related to your question here}
</details>

**Comment by rnicholus** [comment]
I suggest you ensure `val` is _not_ `undefined` before attempting to access a property.

**Comment by mottoregina** [comment]
That is not an answer because it's create by the format methode it self so the message that go's in create an undefined val. So how the hack can you ensure that it is not undefined? 
It looks more that the reason is pore documentation and happy flow programming.

**Comment by rnicholus** [comment]
Sorry, I can't understand anything you're saying here.

**Comment by mottoregina** [comment]
if the server gives a json response back it go's through the qq.format and it chockes on that.
Because it starts to remove the {} brackets from it and it ends in a undefined.
So pore documentation or only happly flow programming without unittesting.

**Comment by rnicholus** [comment]
your report is the first such report, so i can assure you that the issue is very specific to your workflow. Furthermore, you're using an incredibly old version of the library, you haven't pointed to a specific line in the source code, and it's completely unclear how to reproduce. I'm not able to spend any more time on this, but a PR would be welcome.

**Comment by mottoregina** [comment]
It is quite easy reproduce this error use the java server code from the repository and you will see this error happing and open for example chrome develop . So it is not an old version (5.14.5). It is all from the githup repository (https://github.com/FineUploader/server-examples)
the method writeResponse from  UploadReceiver returns json and internally qq.format choke on it.
And there is no documentation on the structuere of the json that should be return and what is except by the javascript code by fine uploader.
I checked all other program languages from the examples to find a better json example but the other langauge don't return any json reponse. There are no examples in other language either. So Java example serverside code is the most completed in that sense.

**Comment by rnicholus** [comment]
All examples return JSON, and there are tons of them in https://github.com/FineUploader/server-examples. 

If Fine Uploader was unable to handle JSON in response to upload requests, this issue tracker would be flooded because *every single app that depends on Fine Uploader would be broken*.

Also, the expected response _is_ documented at https://docs.fineuploader.com/branch/master/endpoint_handlers/traditional.html.

Please stop wasting my time.

**Comment by rnicholus** [comment]
Had you taken the time to fill out a detailed report and not ignore the instructions in the issue tracker, perhaps this could have ended differently for you.
