### ISSUE TITLE
Error : SignatureDoesNotMatch

### ISSUE THREAD

**Issue by rajandotimely** [FineUploader/fine-uploader#1920]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [-] Support request

## Uploader type
- [ ] Traditional
- [-] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.0

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
iOS 9.1.0

#### Exact steps required to reproduce the issue
1. https://github.com/FineUploader/server-examples/blob/master/nodejs/s3/s3handler.js (s3 handler for end point)

Configs changed in s3handler.js
  clientSecretKey = "AKIAISDTN****",
  serverPublicKey = "AKIAISDTN****",
  serverSecretKey = "gfuDjw1J3PIEp+BEb*****",
  expectedBucket = "dotimely-poc",
  expectedHostname = "dotimely-poc.s3.amazonaws.com",
  expectedMinSize = 0,
  expectedMaxSize = 15000000,

2. var uploader = new qq.s3.FineUploader({
      debug: true,
      element: document.getElementById('fine-uploader'),
      objectProperties: {
        region: "us-east-2",
        bucket: 'dotimely-poc',
        host: 's3.us-east-2.amazonaws.com'
      },
      request: {
        endpoint: 'https://s3.us-east-2.amazonaws.com/***-poc',
        accessKey: 'AKIAISDTNBE3****'
      },
      signature: {
        endpoint: '/s3handler',
        version: 4,
      },
      uploadSuccess: {
        endpoint: '/s3handler'
      },
      iframeSupport: {
        localBlankPagePath: '/success.html'
      },
      retry: {
        enableAuto: true // defaults to false
      },
      chunking: {
        enabled: false
      },
      deleteFile: {
        enabled: false,
      },
      validation: {
        minSizeLimit: 0,
        sizeLimit: 15000000 // 50 kB = 50 * 1024 bytes
      }
    });
3. 

####  Fine Uploader

 Using "s3.fine-uploader.min.js"  - javascript file

 HTML template - https://docs.fineuploader.com/quickstart/02-setting_options-s3.html - html code from this page

#### Detailed explanation of the problem

![screen shot 2017-09-19 at 20948 am](https://user-images.githubusercontent.com/32076617/30563879-dd80db5a-9ce0-11e7-9100-e8f498538430.jpg)
</details>

<details>
<summary>Support Request</summary>

I am getting SignatureDoesNotMatch error. What's wrong with the config ?. 
What's the next step i have to take to debug this issue ?.

#### Question
What's wrong with this config ?. How to debug it ?
How to make simple fine uploader s3 handler working with server (node)?

Thanks for your help.
</details>

**Comment by rnicholus** [comment]
I'm not able to find time to troubleshoot. Do let me know if you find a bug in either the client-side or server-side code.

**Comment by msavvy** [comment]
I got the same issue with the following configs on amazon and on client. Please check if there's any configuration and/or code errors.

S3 AWS Settings
==============
S3 Bucket Cors
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <ExposeHeader>ETag</ExposeHeader>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

IAM Group
SavvyDrupal

IAM Group Policy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:PutObject",
            "Resource": "arn:aws:s3:::savvydrupal/*"
        }
    ]
}

IAM Users assigned to group
1. SavvyUploader
2. SavvyDrupalAdmin

// EOF S3 AWS Settings

Client Code
=========
$('#fine-uploader-manual-trigger').fineUploaderS3({
          debug: true,
          request: {
            endpoint: "savvydrupal.s3.amazonaws.com",
            accessKey: "ACCESS_KEY_OF_SavvyUploader",
          },
          signature: {
            endpoint: settings.savvyapplication.signature_s3_cors
          },
          uploadSuccess: {
            endpoint: settings.savvyapplication.signature_s3_cors
          },
          iframeSupport: {
            localBlankPagePath: "success.html"
          },
          objectProperties: {
            key: function(fileId) {
              var uuid = $("#fine-uploader-manual-trigger").fineUploader("getUuid", fileId);

              return uuid;
            }
          },
          validation: {
            allowedExtensions: ["gif", "jpeg", "jpg", "png"],
            acceptFiles: "image/gif, image/jpeg, image/png",
            itemLimit: 5
          },
          retry: {
              enableAuto: false
          },
          chunking: {
            enabled: true
          },
          resume: {
            enabled: true
          },
          paste: {
            targetElement: $(document),
            promptForName: true
          }
        });

// EOF Client Code

Server Code
=============
require '/includes/form.functions.s3.php';

  global $clientPrivateKey, $serverPublicKey, $serverPrivateKey, $expectedBucketName, $expectedMaxSize;
  // These assume you have the associated AWS keys stored in
  // the associated system environment variables
  $clientPrivateKey = 'ACCESS_KEY_OF_SavvyUploader';

  // These two keys are only needed if the delete file feature is enabled
  // or if you are, for example, confirming the file size in a successEndpoint
  // handler via S3's SDK, as we are doing in this example.

  $serverPublicKey = 'ACCESS_KEY_OF_SavvyDrupalAdmin';
  $serverPrivateKey = 'SECRET_KEY_OF_SavvyDrupalAdmin';

  // The following variables are used when validating the policy document
  // sent by the uploader. 
  $expectedHostName = ''; // v4-only

  $expectedBucketName = 'savvydrupal';

  // $expectedMaxSize is the value you set the sizeLimit property of the 
  // validation option. We assume it is `null` here. If you are performing
  // validation, then change this to match the integer value you specified
  // otherwise your policy document will be invalid.
  // http://docs.fineuploader.com/branch/develop/api/options.html#validation-option
  $expectedMaxSize = (isset($_ENV['S3_MAX_FILE_SIZE']) ? $_ENV['S3_MAX_FILE_SIZE'] : null);

  $method = getRequestMethod();

  // This second conditional will only ever evaluate to true if
  // the delete file feature is enabled
  if ($method == "DELETE") {
    deleteObject();
  }
  // This is all you really need if not using the delete file feature
  // and not working in a CORS environment
  else if ($method == 'POST') {

    // Assumes the successEndpoint has a parameter of "success" associated with it,
    // to allow the server to differentiate between a successEndpoint request
    // and other POST requests (all requests are sent to the same endpoint in this example).
    // This condition is not needed if you don't require a callback on upload success.
    if (isset($_REQUEST["success"])) {
      verifyFileInS3(shouldIncludeThumbnail());
    }
    else {
      signRequest();
    }
  }

// EOF Server Code

If there are other things you needed please just tell.

Thank you.

**Comment by msavvy** [comment]
I got the same issue with the following configs on amazon and on client. Please check if there's any configuration and/or code errors on attachment.

Thank you.
[code attachments.txt](https://github.com/FineUploader/fine-uploader/files/1312837/code.attachments.txt)
