### ISSUE TITLE
s3: local signing / redefine the filename before upload

### ISSUE THREAD

**Issue by logemann** [FineUploader/fine-uploader#2015]
## Type of issue
- [x] Question

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

I crawled through the docs and couldnt find any hints to these two questions:

1) Can we provide our local singing function for s3 signing? I already sign my requests for other services on client side with temporary credentials obtained by AWS Cognito. 

2) Is there a way to redefine filenames (object-keys) before upload? 

additionally:

3) What is the best way to donate to this project? This uploader component would be pretty important for my goal and i would like to support if this component will be used.

**Comment by logemann** [comment]
I can answer question 1 myself via
https://docs.fineuploader.com/branch/master/features/no-server-uploads.html

**Comment by rnicholus** [comment]
Question 2: see the setName API method.

Regarding question 3: The S3 demo on the site is currently broken because I stopped paying the AWS bills (and Amazon couldn’t care less about supporting FOSS projects). So if someone wants to offer to pay that ($40/month) we could bring the S3 demo back online.

But mostly this project needs at least one committed maintainer. I don’t use Fine Uploader at my current job, and I’m finding that I have little time and motivation to evolve or even maintain it myself. So if you know of any suitable and interested candidates who are very strong on the web dev side, please point them my way. Being a visible maintainer to a large project opened a lot of doors for me, so that is one big benefit.

**Comment by logemann** [comment]
Question 2: thanks. Have seen some examples here and there with key() function. 

Regarding maintaining the library. Unfortunately i am not good enough on the JS side, coming from a more Java enterprise background. Still fighting with react.

Speaking of react. I really searched a lot. It seems there is no good example on how to use client side only S3 upload with integrated singing. The only one i found is quite old (https://github.com/FineUploader/integration-examples/blob/master/src/s3-no-server/fineuploader-glue.js) and not react based. 

Is there a react example somewhere? Also i dont get why i need a signature endpoint when i can already supply credentials via "credentials" config key. Thought that the signing can be on the client which by looking at the code from FineUploaderS3 seems to be the case.

Regarding backing this project. You should consider using https://opencollective.com. Its pretty easy for backers to support projects. I ve done it with mobx recently. Perhaps you might consider this.
