### ISSUE TITLE
Missing querySelectorAll in IE9 with jquery fineuploader

### ISSUE THREAD

**Issue by akre54** [FineUploader/fine-uploader#535]
Ran into this while testing with fineuploader on IE9: 

```
Unable to get value of the property 'querySelectorAll': object is null or undefined 
jquery.fineuploader-3.0.min.js, line 38 character 98
```

It's a FUB button that I'm using the jquery plugin on. Will get more info if you need it.

**Comment by farhantahseen** [comment]
I am using older version and I am facing the same issue but in all browsers. It occurs when if you press delete link before upload complete. after 2,3 times uploading stopped with following error in console.
 TypeError: a is undefined (file: jquery.fineuploader.min.js)
if (a.querySelectorAll){ 

According to my finding if i am not wrong each time when upload starts till complete there are multi status for a, from li to li.qq-upload-success
please help.
getByClass: function(b) {
            var c, d = [];
            if (a.querySelectorAll) //this line creating issue
                return a.querySelectorAll("." + b);
            c = a.getElementsByTagName("*");
            qq.each(c, function(a, c) {
                qq(c).hasClass(b) && d.push(c)
            });
            return d
        }

**Comment by rnicholus** [comment]
It sounds like you are indeed running a very old version.  I would suggest upgrading.

**Comment by farhantahseen** [comment]
Everything is going good, if you suggest anything in this regard i will be thankful to you dear

**Comment by rnicholus** [comment]
I suggest you upgrade and see if the issue persists.

**Comment by farhantahseen** [comment]
basically I am using jquery-uberuploadcropper library to upload, crop and drag images with a lot of customize code therefor I was asking for a quick fix. Anyhow I will upgrade all libraries then if there would be any issue I will let you know, Thanks

**Comment by rnicholus** [comment]
According to the web page for that library, Fine Uploader is not used.

**Comment by farhantahseen** [comment]
I think they are using fine uploader: below is the link

https://github.com/trentrichardson/UberUploadCropper

**Comment by rnicholus** [comment]
Ah, looks like the web page simply hasn’t been updated.  I suspect uploadify was dropped due to [the abysmal quality of the library](http://www.uploadify.com/forum/#/discussion/comment/20555).  

There are quite a few breaking changes between 3.0 (the version uberuploadcropper is using) and the current version (5.1.3).  It’s possible uberUploadCropper code may need to be changed after the upgrade as well.

**Comment by farhantahseen** [comment]
That's mean my issue will be resolved if uberUploaderCropper will update their library?

**Comment by rnicholus** [comment]
It's possible, but there aren't any commits to that library since early 2013, so that probably won't happen.  If you want to continue to use uber cropper, you'll probably need to fork the repo, update Fine Uploader, and then adjust the uber codebase to account for the changes in Fine Uploader since v3.

**Comment by farhantahseen** [comment]
ok thanks a lot for your kind support

**Comment by rnicholus** [comment]
Sure.  The Fine Uploader docs site includes extensive documentation for [breaking changes in 4.0](http://docs.fineuploader.com/upgrading-to-4.html) as well as [breaking changes in 5.0](http://docs.fineuploader.com/upgrading-to-5.html).  This should help you make the proper adjustments to uber after you upgrade Fine Uploader.
