### ISSUE TITLE
Timeout for bad internet connection

### ISSUE THREAD

**Issue by Maigre** [FineUploader/fine-uploader#743]
Hi there !
Thanks for your uploader, it's a really big help :)

The problem: 
I try to upload big files over bad internet connection (chunks are usefull !)
but if my connection drop in the middle of the upload, 
the ajax POST of the current chunk doesn't recieve answer from the server,
and it continue to wait... (regardless if the connection is back or not)
is it possible to set up a timeout on the ajax waiting, 
so if the connection has dropped it start to retry (in case the connection is back)
and finally push an error if it is still impossible to reach the server 
so the client can check his connection and then manually retry ?

Thanks !

Best Regards,

Thomas

**Comment by rnicholus** [comment]
XHR timeouts are now supported in Chrome/Safari, so perhaps we should look into implementing this.

**Comment by rnicholus** [comment]
I'm going to look into this as part of 5.11.9, since network errors (particularly pulling the connection mid-upload) causes the upload to hang for a _long_ time. That seems like a bug to me, and if we can make this less of an issue, even in a subset of browsers, that seems like a big win.

**Comment by rnicholus** [comment]
I think I now remember why I kicked this can down the road for so long. Setting a timeout on an `XMLHttpRequest` instance does not function as one would expect (or at least as I would expect). The clock starts ticking as soon as the request is sent. If the request does not complete before the timeout expires, the browser cancels the request. I would expect the request to timeout only if there is no HTTP traffic for a length of time equal to the timeout value. 

The problem with the standardized behavior of `XMLHttpRequest.timeout` is that it may be very tricky to determine an appropriate and effective value. When you choose a timeout value, you have to consider that some internet connections are faster than others. For example, if you choose a timeout value of 5 seconds, with a chunk size of 5 MB, the request will _always_ timeout for files being sent from a typical home internet connection with available upstream bandwidth of 4 Mbps, since each 5 MB chunk will take about 10 seconds to complete.

In light of this, I'm strongly considering abandonment of this "feature". Another option: advise integrators to set a reasonably high value, but this honestly seems like it may cause more problems than it solves. I'm open to input, but I'm putting this on hold for now.
