### ISSUE TITLE
13 - Populate file list with previously uploaded files

### ISSUE THREAD

**Issue by number0** [FineUploader/fine-uploader#784]
Using the jQuery wrapped latest version 
How to populate the file list with files already uploaded to server?

Adding my own items to the list/UI via jQuery is not option because I lose validation rules

**Comment by alphestdev** [comment]
Can the files be added without an ajax request? I need a simple way to add already uploaded file records for a common scenario:
1. Files are selected and uploaded using Fine-Uploader
2. The form is POSTed manually using submit button, but did not pass server side validation.
3. Server returns the form still in edit mode, for the user to correct his errors. (Fine Uploader list is empty here. An AJAX request for initial file list cannot be populated server-side because $_POST is already cleared in step 2)

Is there something like `addFileRecord(files_array)`?

This should be really simple, because this functionality is already written and works when AJAX request is processed.

I tried 
```
      var id = uploader._addCannedFile({
        uuid: 'some-test-uuid',
        name: 'TEST FILE NAME.file',
        size: 1000,
        thumnailUrl: iconPath +'Attachment_File_32.png'
      });
      uploader._addToList(id, uploader.getName(id));
```
The file record is added, but not fully functional. There is no thumbnail, all the buttons like retry and cancel are visible and no events are attached. For example when I press delete, nothing happens. Can you explain how this can be done?

**Comment by rnicholus** [comment]
If you set the [`session.refreshonReset` option](http://docs.fineuploader.com/branch/master/api/options.html#session.refreshOnReset) to true, Fine Uploader will send a new GET request for the initial file list when you call the [`reset` API method](http://docs.fineuploader.com/branch/master/api/methods.html#reset).

For any more questions regarding use of Fine Uploader, please post on Stack Overflow under the fine-uploader tag.

**Comment by ludofleury** [comment]
@alphestdev Ran to the same issue today, here the not so nice hack for fine uploader UI:

```
var uploader = ....
var id = uploader._addCannedFile({
                uuid: 'an-uuid',
                name: 'test.ext',
                size: 1000
            })
            uploader._templating.addCacheToDom();
```

beware it call internal API and should not be trusted when you update the lib etc...
I hope it could be implemented in the next version.

**Comment by rnicholus** [comment]
Issue #1191 covers exposing a public API method that would allow canned files to be easily added from any source. I've moved that case into version 5.6.0, which I will begin working on immediately. Please follow that case for updates.

**Comment by Harrrrry** [comment]
Please explain me, how can i show the files already uploaded to server in fine uploader.
How and where i need to change the code.
I am very much confused
