### ISSUE TITLE
How to set enabled o disabled the FineUpload?.

### ISSUE THREAD

**Issue by EddGarciaG88** [FineUploader/fine-uploader#793]
I have an option buttons: Yes and No. If i check "Yes" , I want to set enabled the fineupload, If i check "No" I want to set disabled the fineupload. By default, the option "No" will be selected when the page load.

**Comment by tsvetelin-pavlov** [comment]
We have a dialog, where user had to make two choices and upload a file.
The file must not be uploaded without those options chosen.
Since it is an Upload dialog, we want the uploader to be visible in order to visually hint, that the user is on the correct screen. So we need the enable/disable option.
I've tried setting it with jQuery, the uploader renders as disabled, but even then I can upload files. How can I  disable uploading?
