### ISSUE TITLE
Not able to select multiple files (images) in Android 4.2.2 on demos

### ISSUE THREAD

**Issue by ollyculverhouse** [FineUploader/fine-uploader#840]
I am unable to select multiple files (in this case images) when using your demos on the site in stock Android 4.2.2.

I already use fineuploader for a site and am seeing the same behaviour.

**Comment by anbarasuthresnathan** [comment]
Anyone found the solution how to select the multiple file selection

**Comment by rnicholus** [comment]
You will be able to do this once it is supported by the OS. There is no "workaround".

**Comment by anbarasuthresnathan** [comment]
Thanks

**Comment by ruinunes** [comment]
Still unable to perform multiple uploads (with Chrome 43 and Android 5.0.2).

**Comment by rnicholus** [comment]
@ruinunes It is allegedly supported in Android 5.x, but only with the Chrome browser on Android. I haven't verified. Source: http://caniuse.com/#feat=input-file-multiple

**Comment by ruinunes** [comment]
Seems to be up to the android browser app developers to enable a parameter in the intent call to grab multiple files instead of a single file, from an available OS file picker. AFAIK, this ability is enabled since android 4.4.4 (although we run our android tablet from 5.0.2) but not implemented by the browsers I have tested.
Yep, the web says Chrome 49 solves this, albeit, for Chrome only. I will do an OS and and Chrome update soon.

**Comment by ruinunes** [comment]
Got multiple files upload this way on Android:
Hit your normal <input type='file' multiple> button. File picker appears: do a long press on a file to select it, then select other files. On the top bar an "Open" appears, select it and then multiple files are added to the files collection.
